# Generated by Django 5.1.3 on 2024-12-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ad01', '0002_user_salary_user_type_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='manager',
            field=models.IntegerField(default=0),
        ),
    ]
